### ISSUE TITLE
Chef failing due to MongoDB - NoMethodError: undefined method `helpers'

### ISSUE THREAD

**Issue by andrewtennison** [aderyabin/rove#43]
ShareID = 92eac5e2df71f6c651f7e4d5b9d31a08

Doing a manual install and it fails on vagrant up, something to do with mongo, wonder if there is a version issue?

From cli output

Recipe Compile Error in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/mongodb/recipes/default.rb

Relevant File Content:
/tmp/vagrant-chef-3/chef-solo-1/cookbooks/mongodb/recipes/install.rb:
23>>   helpers MongoDBConfigHelpers

FATAL: NoMethodError: undefined method `helpers' for Chef::Resource::Template

**Comment by goliatone** [comment]
Same issue here.

```
Mac OSx v 10.9.5
Vagrant 1.7.2
ruby 2.0.0p643
```

**Comment by rex** [comment]
Same issue here as well. 

System Info
---

```
p-rex at The Death Star  ~ 
👽  vagrant -v
Vagrant 1.6.5
p-rex at The Death Star  ~ 
👽  ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
p-rex at The Death Star  ~ 
👽  system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.10.3 (14D131)
      Kernel Version: Darwin 14.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Sq1PierceMoore
      User Name: Pierce Moore (pimoore)
      Secure Virtual Memory: Enabled
      Time since boot: 2 days 15:54
```

Error Output (Unabridged)
---

```
==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef-4/chef-solo-1/cookbooks/mongodb/recipes/default.rb
==> default: ================================================================================
==> default:
==> default:
==> default: NoMethodError
==> default: -------------
==> default: undefined method `helpers' for Chef::Resource::Template
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef-4/chef-solo-1/cookbooks/mongodb/recipes/install.rb:23:in `block in from_file'
==> default:   /tmp/vagrant-chef-4/chef-solo-1/cookbooks/mongodb/recipes/install.rb:14:in `from_file'
==> default:   /tmp/vagrant-chef-4/chef-solo-1/cookbooks/mongodb/recipes/default.rb:22:in `from_file'
==> default:
==> default:
==> default: Relevant File Content:
==> default:
==> default: ----------------------
==> default: /tmp/vagrant-chef-4/chef-solo-1/cookbooks/mongodb/recipes/install.rb:
==> default:
==> default:  16:    source node['mongodb']['dbconfig_file_template']
==> default:  17:    group node['mongodb']['root_group']
==> default:  18:    owner 'root'
==> default:  19:    mode 0644
==> default:  20:    variables(
==> default:  21:      :config => node['mongodb']['config']
==> default:  22:    )
==> default:  23>>   helpers MongoDBConfigHelpers
==> default:  24:    action :create_if_missing
==> default:  25:  end
==> default:  26:
==> default:  27:  # and we install our own init file
==> default:  28:  if node['mongodb']['apt_repo'] == 'ubuntu-upstart'
==> default:  29:    init_file = File.join(node['mongodb']['init_dir'], "#{node['mongodb']['default_init_name']}.conf")
==> default:  30:    mode = '0644'
==> default:  31:  else
==> default:  32:    init_file = File.join(node['mongodb']['init_dir'], "#{node['mongodb']['default_init_name']}")
==> default:
==> default:
==> default:
==> default: [2015-04-12T06:38:54+00:00] ERROR: Running exception handlers
==> default: [2015-04-12T06:38:54+00:00] ERROR: Exception handlers complete
==> default: [2015-04-12T06:38:54+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-04-12T06:38:54+00:00] FATAL: NoMethodError: undefined method `helpers' for Chef::Resource::Template
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by 3manuek** [comment]
helpers.rb is missing on the mongodb recipes.

**Comment by 3manuek** [comment]
Downloaded https://supermarket.chef.io/cookbooks/mongodb/versions/0.16.0 (0.16.1 was failing too) into coobooks, uncompressed and it works.

**Comment by rex** [comment]
@3manuek Thanks for doing the legwork on that! I took a look at the supermarket for the MongoDB recipe but couldn't locate an issue tracker affiliated with it that I could post this issue to. I'll look around and see if I can come up with something.

**Comment by rex** [comment]
Alright, done. The repository appears to be barely maintained, though, so I'm not sure how expedient the resolution process will be on that end. Perhaps it would be quicker for Rove to just specify `v0.16.0` temporarily until the issue is resolved on the recipe end, @3manuek?

**Comment by 3manuek** [comment]
@rex I think, yes. The best they can do is to stick to v0.16.0 temporarily or until a new version with a fix comes up. I can write the helpers recipe, it is not really hard to do, the problem is that I don't know if they are maintaining it and if they will push the pull request. 
Actually, at a first glance, looks very alpha to me.

**Comment by rex** [comment]
@3manuek I totally agree with you. As you can see in my comment I posted in that thread I didn't really mince words when it came to the responsibility of the developers to maintain the most-used MongoDB recipe in the supermarket. It does look shockingly ill-maintained, and it's a bit disconcerting to be honest.

For what my personal opinion is worth, I think that it's in the best interest of Rove.io and its users to force the MongoDB cookbook to version `0.16.0` until a fix is issued on the other side. Is there a way to make that happen? Obviously as a maintainer of Rove it's your call, but I do think it would seriously improve the user experience :) 

Thank you for your attention to this issue, @3manuek!

**Comment by rex** [comment]
Quick update: Unless I'm mistaken, the fix I am campaigning for can be made on this line: https://github.com/aderyabin/rove/blob/master/packages/mongodb.rb#L5 by replacing 

```
cookbook 'mongodb'
```

with 

```
cookbook 'mongodb', '~> 0.16.0'
```

**Comment by 3manuek** [comment]
\o/ You're welcome! Rove rocks!

**Comment by rex** [comment]
I completely agree! Should I submit a pull request for the MongoDB cookbook version specification or would you prefer to attack the issue in a different way, @3manuek?

**Comment by cjsauer** [comment]
I'd like to share my little workaround for anyone using the web app of Rove also having this issue. It's basically a culmination of what's been stated above. 

In the Cheffile, before you do any vagrant provisioning, you can replace this line: 

`cookbook "mongodb", {}`

with this: 

`cookbook "mongodb", {:github=>"edelight/chef-mongodb", :ref=>"0.16.0"}`

and now run `curl -L http://rove.io/install | bash` as stated on Rove to provision and start the box.

**Comment by rex** [comment]
@cjsauer That's an excellent solution. I was hoping for Rove to automatically handle that for now due to AUL, a term I just invented that stands for "**A**verage **U**ser **L**aziness".

**Comment by amoose** [comment]
workaround successful, thanks @rex and @cjsauer
