### ISSUE TITLE
Chef fails

### ISSUE THREAD

**Issue by Jakobud** [aderyabin/rove#46]
There is the `Cheffile`

```
# encoding: utf-8

site 'http://community.opscode.com/api/v1'

cookbook "apt"
cookbook "git", {}
cookbook "nodejs", {:github=>"mdxp/nodejs-cookbook"}
cookbook "nginx", {}
cookbook "mysql", {}
cookbook "vim", {}
```

Here is the `Vagrantfile`

```
# encoding: utf-8
# This file originally created at http://rove.io/1830e30d8791ee5734a7513a0433ec8c

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "opscode-ubuntu-12.04_chef-11.4.0"
  config.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.0.box"
  config.ssh.forward_agent = true

  config.vm.network :forwarded_port, guest: 80, host: 8888

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks"]
    chef.add_recipe :apt
    chef.add_recipe 'git'
    chef.add_recipe 'nodejs'
    chef.add_recipe 'nginx'
    chef.add_recipe 'mysql::server'
    chef.add_recipe 'vim'
    chef.json = {
      :git   => {
        :prefix => "/usr/local"
      },
      :nginx => {
        :dir                => "/etc/nginx",
        :log_dir            => "/var/log/nginx",
        :binary             => "/usr/sbin/nginx",
        :user               => "www-data",
        :init_style         => "runit",
        :pid                => "/var/run/nginx.pid",
        :worker_connections => "1024"
      },
      :mysql => {
        :server_root_password   => "password",
        :server_repl_password   => "password",
        :server_debian_password => "password",
        :service_name           => "mysql",
        :basedir                => "/usr",
        :data_dir               => "/var/lib/mysql",
        :root_group             => "root",
        :mysqladmin_bin         => "/usr/bin/mysqladmin",
        :mysql_bin              => "/usr/bin/mysql",
        :conf_dir               => "/etc/mysql",
        :confd_dir              => "/etc/mysql/conf.d",
        :socket                 => "/var/run/mysqld/mysqld.sock",
        :pid_file               => "/var/run/mysqld/mysqld.pid",
        :grants_path            => "/etc/mysql/grants.sql"
      }
    }
  end
end

```

I get the following:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'opscode-ubuntu-12.04_chef-11.4.0' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'opscode-ubuntu-12.04_chef-11.4.0' (v0) for provider: virtualbox
    default: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.0.box
==> default: Successfully added box 'opscode-ubuntu-12.04_chef-11.4.0' (v0) for 'virtualbox'!
==> default: Importing base box 'opscode-ubuntu-12.04_chef-11.4.0'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: rove-1830e30d8791ee5734a7513a0433ec8c_default_1440108155858_27198
==> default: Clearing any previously set forwarded ports...
==> default: The cookbook path '/Users/user1/Downloads/rove-1830e30d8791ee5734a7513a0433ec8c/cookbooks' doesn't exist. Ignoring...
```

In the downloaded zip, the `Vagrantfile` and `Cheffile` were both in the same, base directory. So next I created a `cookbooks` directory and moved the `Cheffile` into there. Running `vagrant up` again:

```
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: Starting Chef Client, version 11.4.0
==> default: [2015-08-20T22:03:52+00:00] INFO: *** Chef 11.4.0 ***
==> default: [2015-08-20T22:03:53+00:00] INFO: Setting the run_list to ["recipe[apt]", "recipe[git]", "recipe[nodejs]", "recipe[nginx]", "recipe[mysql::server]", "recipe[vim]"] from JSON
==> default: [2015-08-20T22:03:53+00:00] INFO: Run List is [recipe[apt], recipe[git], recipe[nodejs], recipe[nginx], recipe[mysql::server], recipe[vim]]
==> default: [2015-08-20T22:03:53+00:00] INFO: Run List expands to [apt, git, nodejs, nginx, mysql::server, vim]
==> default: [2015-08-20T22:03:53+00:00] INFO: Starting Chef Run for vagrant.vm
==> default: [2015-08-20T22:03:53+00:00] INFO: Running start handlers
==> default: [2015-08-20T22:03:53+00:00] INFO: Start handlers complete.
==> default: [2015-08-20T22:03:53+00:00] ERROR: Running exception handlers
==> default: [2015-08-20T22:03:53+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated
==> default: [2015-08-20T22:03:53+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-08-20T22:03:53+00:00] FATAL: ArgumentError: You must specify at least one cookbook repo path
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

And here is that stack trace:

```
sudo cat /var/chef/cache/chef-stacktrace.out
Generated at 2015-08-20 22:03:53 +0000
ArgumentError: You must specify at least one cookbook repo path
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/cookbook_loader.rb:43:in `initialize'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:212:in `new'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:212:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:467:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:200:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application.rb:190:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/solo.rb:239:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/solo.rb:231:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/solo.rb:231:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application.rb:73:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:23:in `load'
/usr/bin/chef-solo:23:in `<main>'
```

What am I missing here?

**Comment by cristianmartinez** [comment]
I have the same problem.... +1

**Comment by mr-White** [comment]
+1
